sudo: required
env:
  - _FORCE_LOGS=1 PLATFORM_VERSION=10.2 TEST=unit
  - _FORCE_LOGS=1 PLATFORM_VERSION=10.2 TEST=functional/basic
  - _FORCE_LOGS=1 PLATFORM_VERSION=10.2 TEST=functional/driver
  - _FORCE_LOGS=1 PLATFORM_VERSION=10.2 TEST=functional/web
  - _FORCE_LOGS=1 PLATFORM_VERSION=10.2 TEST=functional/long
language:
  - objective-c
os: osx
osx_image: xcode8.2
git: # Handle git submodules yourself
  submodules: false
before_install:
  - nvm install 4
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  # code from http://stackoverflow.com/a/24600210/375688
  - sed -i '' 's/git@github.com:/https:\/\/github.com\//' /Users/travis/build/appium/appium-xcuitest-driver/.gitmodules
  - git submodule update --init --recursive
  - pushd WebDriverAgent && ./Scripts/bootstrap.sh -d && popd
  - brew install ios-webkit-debug-proxy
before_script:
  - node --version
  - npm install
  - npm install -g gulp
  - npm install -g mocha
  - node --version # just print out the node version, so we know for sure
  - gulp transpile
script:
  - gulp eslint && mocha -t 480000 --recursive build/test/$TEST -g @skip-ci -i
